### ISSUE TITLE
Autostart in background

### ISSUE THREAD

**Issue by smbln** [vorlovsky/AppAutostart-ANE#2]
Hi, could you please add a feature to choose between autostart in foreground or background?
cheers

**Comment by vorlovsky** [comment]
Hi!

Don't know, what's the autostart in background speaking about Android activity-based app? How does it look like?

**Comment by smbln** [comment]
I think launch app on boot and minimize it to background.

**Comment by vorlovsky** [comment]
IMHO, minimizing an app is a separate action not to be covered in this ANE.
