### ISSUE TITLE
Add 64bits support

### ISSUE THREAD

**Issue by lwmirkk** [vorlovsky/AppAutostart-ANE#3]
Hi!

Please add the 64 bus support with new AIR v33 SDK by Harman.

Thanks a lot.

**Comment by vorlovsky** [comment]
Hi!

I've added a new [branch ](https://github.com/vorlovsky/AppAutostart-ANE/tree/feature/android_64bit_support) containing changes related to android 64 bit support.
Unfortunately, I'm not able to check it properly on real devices. Can you do it?
